
const AvatarEnum = require('../enums/AvatarEnum');
const AnimationEnum = require('../enums/AnimationEnum');
const AnimationBlockTimerEnum = require('../enums/AnimationBlockTimerEnum');

class InteractionsBlockActionsMap {
    static get(interactionType) {
        const data = {
            [AnimationEnum.INTERACTION_KISS]: {
                actions: [
                    AnimationEnum.UPPERCUT,
                    AnimationEnum.WALK,
                    AnimationEnum.LOOK,
                    AnimationEnum.LEAVE_AREA,
                    AnimationEnum.AVATAR_KISS,
                    AnimationEnum.AVATAR_DRINK,
                    AnimationEnum.AVATAR_ROSE,
                    AnimationEnum.AVATAR_LOVE,
                    AnimationEnum.AVATAR_SPIT,
                    AnimationEnum.AVATAR_FART,
                    AnimationEnum.AVATAR_PROVOKE,
                    AnimationEnum.AVATAR_FLY,
                    AnimationEnum.AVATAR_DOWN_TALK,
                    AnimationEnum.AVATAR_UP_TALK,
                    AnimationEnum.AVATAR_LEFT_TALK,
                    AnimationEnum.AVATAR_RIGHT_TALK,
                    AnimationEnum.AVATAR_LEFTDOWN_TALK,
                    AnimationEnum.AVATAR_RIGHTDOWN_TALK,
                    AnimationEnum.AVATAR_LEFTUP_TALK,
                    AnimationEnum.AVATAR_RIGHTUP_TALK,
                    AnimationEnum.COCONUT,
                    AnimationEnum.INTERACTION_KISS,
                    AnimationEnum.INTERACTION_DRINK,
                    AnimationEnum.INTERACTION_ROSE
                ],
                time: {
                    [AvatarEnum.BOOMER]: AnimationBlockTimerEnum.BOOMER_KISS,
                    [AvatarEnum.BRUJITA]: AnimationBlockTimerEnum.BRUJITA_KISS,
                    [AvatarEnum.CHOLO]: AnimationBlockTimerEnum.CHOLO_KISS,
                    [AvatarEnum.EMPOLLON]: AnimationBlockTimerEnum.EMPOLLON_KISS,
                    [AvatarEnum.GATA]: AnimationBlockTimerEnum.GATA_KISS,
                    [AvatarEnum.GHOST]: AnimationBlockTimerEnum.GHOST_KISS,
                    [AvatarEnum.INDIA]: AnimationBlockTimerEnum.INDIA_KISS,
                    [AvatarEnum.LILIAN]: AnimationBlockTimerEnum.LILIAN_KISS,
                    [AvatarEnum.MARSU]: AnimationBlockTimerEnum.MARSU_KISS,
                    [AvatarEnum.MODERN]: AnimationBlockTimerEnum.MODERN_KISS,
                    [AvatarEnum.NINJA]: AnimationBlockTimerEnum.NINJA_KISS,
                    [AvatarEnum.RASTA]: AnimationBlockTimerEnum.RASTA_KISS,
                    [AvatarEnum.SKELETON]: AnimationBlockTimerEnum.SKELETON_KISS,
                    [AvatarEnum.WEREWOLF]: AnimationBlockTimerEnum.WEREWOLF_KISS,
                    [AvatarEnum.WRAITH]: AnimationBlockTimerEnum.WRAITH_KISS,
                    [AvatarEnum.YAYO]: AnimationBlockTimerEnum.YAYO_KISS,
                    [AvatarEnum.ZOMBIE]: AnimationBlockTimerEnum.ZOMBIE_KISS,
                }
            },
            [AnimationEnum.INTERACTION_DRINK]: {
                actions: [
                    AnimationEnum.UPPERCUT,
                    AnimationEnum.WALK,
                    AnimationEnum.LOOK,
                    AnimationEnum.LEAVE_AREA,
                    AnimationEnum.AVATAR_KISS,
                    AnimationEnum.AVATAR_DRINK,
                    AnimationEnum.AVATAR_ROSE,
                    AnimationEnum.AVATAR_LOVE,
                    AnimationEnum.AVATAR_SPIT,
                    AnimationEnum.AVATAR_FART,
                    AnimationEnum.AVATAR_PROVOKE,
                    AnimationEnum.AVATAR_FLY,
                    AnimationEnum.AVATAR_DOWN_TALK,
                    AnimationEnum.AVATAR_UP_TALK,
                    AnimationEnum.AVATAR_LEFT_TALK,
                    AnimationEnum.AVATAR_RIGHT_TALK,
                    AnimationEnum.AVATAR_LEFTDOWN_TALK,
                    AnimationEnum.AVATAR_RIGHTDOWN_TALK,
                    AnimationEnum.AVATAR_LEFTUP_TALK,
                    AnimationEnum.AVATAR_RIGHTUP_TALK,
                    AnimationEnum.COCONUT,
                    AnimationEnum.INTERACTION_KISS,
                    AnimationEnum.INTERACTION_DRINK,
                    AnimationEnum.INTERACTION_ROSE
                ],
                time: {
                    [AvatarEnum.BOOMER]: AnimationBlockTimerEnum.BOOMER_DRINK,
                    [AvatarEnum.BRUJITA]: AnimationBlockTimerEnum.BRUJITA_DRINK,
                    [AvatarEnum.CHOLO]: AnimationBlockTimerEnum.CHOLO_DRINK,
                    [AvatarEnum.EMPOLLON]: AnimationBlockTimerEnum.EMPOLLON_DRINK,
                    [AvatarEnum.GATA]: AnimationBlockTimerEnum.GATA_DRINK,
                    [AvatarEnum.GHOST]: AnimationBlockTimerEnum.GHOST_DRINK,
                    [AvatarEnum.INDIA]: AnimationBlockTimerEnum.INDIA_DRINK,
                    [AvatarEnum.LILIAN]: AnimationBlockTimerEnum.LILIAN_DRINK,
                    [AvatarEnum.MARSU]: AnimationBlockTimerEnum.MARSU_DRINK,
                    [AvatarEnum.MODERN]: AnimationBlockTimerEnum.MODERN_DRINK,
                    [AvatarEnum.NINJA]: AnimationBlockTimerEnum.NINJA_DRINK,
                    [AvatarEnum.RASTA]: AnimationBlockTimerEnum.RASTA_DRINK,
                    [AvatarEnum.SKELETON]: AnimationBlockTimerEnum.SKELETON_DRINK,
                    [AvatarEnum.WEREWOLF]: AnimationBlockTimerEnum.WEREWOLF_DRINK,
                    [AvatarEnum.WRAITH]: AnimationBlockTimerEnum.WRAITH_DRINK,
                    [AvatarEnum.YAYO]: AnimationBlockTimerEnum.YAYO_DRINK,
                    [AvatarEnum.ZOMBIE]: AnimationBlockTimerEnum.ZOMBIE_DRINK,
                }
            },
            [AnimationEnum.INTERACTION_ROSE]: {
                actions: [
                    AnimationEnum.UPPERCUT,
                    AnimationEnum.WALK,
                    AnimationEnum.LOOK,
                    AnimationEnum.LEAVE_AREA,
                    AnimationEnum.AVATAR_KISS,
                    AnimationEnum.AVATAR_DRINK,
                    AnimationEnum.AVATAR_ROSE,
                    AnimationEnum.AVATAR_LOVE,
                    AnimationEnum.AVATAR_SPIT,
                    AnimationEnum.AVATAR_FART,
                    AnimationEnum.AVATAR_PROVOKE,
                    AnimationEnum.AVATAR_FLY,
                    AnimationEnum.AVATAR_DOWN_TALK,
                    AnimationEnum.AVATAR_UP_TALK,
                    AnimationEnum.AVATAR_LEFT_TALK,
                    AnimationEnum.AVATAR_RIGHT_TALK,
                    AnimationEnum.AVATAR_LEFTDOWN_TALK,
                    AnimationEnum.AVATAR_RIGHTDOWN_TALK,
                    AnimationEnum.AVATAR_LEFTUP_TALK,
                    AnimationEnum.AVATAR_RIGHTUP_TALK,
                    AnimationEnum.COCONUT,
                    AnimationEnum.INTERACTION_KISS,
                    AnimationEnum.INTERACTION_DRINK,
                    AnimationEnum.INTERACTION_ROSE
                ],
                time: {
                    [AvatarEnum.BOOMER]: AnimationBlockTimerEnum.BOOMER_ROSE,
                    [AvatarEnum.BRUJITA]: AnimationBlockTimerEnum.BRUJITA_ROSE,
                    [AvatarEnum.CHOLO]: AnimationBlockTimerEnum.CHOLO_ROSE,
                    [AvatarEnum.EMPOLLON]: AnimationBlockTimerEnum.EMPOLLON_ROSE,
                    [AvatarEnum.GATA]: AnimationBlockTimerEnum.GATA_ROSE,
                    [AvatarEnum.GHOST]: AnimationBlockTimerEnum.GHOST_ROSE,
                    [AvatarEnum.INDIA]: AnimationBlockTimerEnum.INDIA_ROSE,
                    [AvatarEnum.LILIAN]: AnimationBlockTimerEnum.LILIAN_ROSE,
                    [AvatarEnum.MARSU]: AnimationBlockTimerEnum.MARSU_ROSE,
                    [AvatarEnum.MODERN]: AnimationBlockTimerEnum.MODERN_ROSE,
                    [AvatarEnum.NINJA]: AnimationBlockTimerEnum.NINJA_ROSE,
                    [AvatarEnum.RASTA]: AnimationBlockTimerEnum.RASTA_ROSE,
                    [AvatarEnum.SKELETON]: AnimationBlockTimerEnum.SKELETON_ROSE,
                    [AvatarEnum.WEREWOLF]: AnimationBlockTimerEnum.WEREWOLF_ROSE,
                    [AvatarEnum.WRAITH]: AnimationBlockTimerEnum.WRAITH_ROSE,
                    [AvatarEnum.YAYO]: AnimationBlockTimerEnum.YAYO_ROSE,
                    [AvatarEnum.ZOMBIE]: AnimationBlockTimerEnum.ZOMBIE_ROSE,
                }
            }
        };
        return data[interactionType] || null;
    }
}

module.exports = InteractionsBlockActionsMap;