import { test, expect } from '@playwright/test'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import fs from 'node:fs'
import sharp from 'sharp'
import { buildSolidRgbaBuffer } from '../scripts/lib/pixelColorMatch.cjs'
import { diffRgbaBuffers } from '../src/shared/assetPipeline/compareRasters.js'

// design.md §10/§11: the resolved-state gate. Every assertion below reads
// `window.__avatarHarness.readState(...)` — resolved container child order, computed x/y/depth,
// live sequence/tint state — never a pure function fed hand-built fixtures.
//
// tasks.md slice 21 task 1: R1-R13 are generated by `describeCharacterMatrix(character,
// avatarId, options)` instead of being hardcoded to `rasta` — this is design.md's R19, "the
// roster matrix": every migrated character passes all 8 directions as an EXECUTED fact, not an
// intention. Each later migration slice (22-31) calls `describeCharacterMatrix` again for its
// own character(s) with that character's own compiled accessory keys, per tasks.md slice 21
// task 9. Today only `rasta` is migrated, so the matrix has one row — the parameterization
// itself, not the roster breadth, is this slice's deliverable.

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const DIRECTIONS = ['down', 'downright', 'right', 'upright', 'up', 'upleft', 'left', 'downleft']
const RIGHT_FACING_DIRECTIONS = new Set(['right', 'downright', 'upright'])

// Antisymmetric mirror pairing (design.md §9/R5): a direction not in this map mirrors itself
// (down/up have no left-right counterpart to flip against).
const MIRROR_OF = {
  down: 'down',
  up: 'up',
  left: 'right',
  right: 'left',
  downleft: 'downright',
  downright: 'downleft',
  upleft: 'upright',
  upright: 'upleft',
}

// BLOCKER fix (2026-08-18): UserIdleAnimation.getTextureKey's own key naming per direction — a
// right-family direction's OWN idle key name is NOT its spec-name with "_idle" appended
// ("downright" -> "rightdown_idle", not "downright_idle"). Needed to assert, per direction, that
// the resolved sequence key is the direction's OWN key (never silently degraded to a DIFFERENT
// idle, e.g. down_idle) and that its mirror source is the correct left-family counterpart.
const DIRECTION_TO_IDLE_KEY = {
  down: 'down_idle',
  downright: 'rightdown_idle',
  right: 'right_idle',
  upright: 'rightup_idle',
  up: 'up_idle',
  upleft: 'leftup_idle',
  left: 'left_idle',
  downleft: 'leftdown_idle',
}

const CRY_EMOJI_ID = 3 // AvatarEmojisEnum.CRY -> "llorar" (universal across characters, fact K)

const CENTER_X_TOL = 0.5 // real px — accumulated floating rounding across the pivot chain
const SHADOW_Y_BAND = 20 // real px — "within a band of the shadow centre" (design.md R5)

let socketCounter = 0

function loadAccessoryManifest(character, kind, key) {
  return JSON.parse(
    fs.readFileSync(
      path.join(
        __dirname,
        `../src/assets/game/accessories/${kind}/${character}/${key}/${key}.accessory.json`
      ),
      'utf8'
    )
  )
}

/**
 * Generates one `test.describe(character, ...)` block covering R1-R13 for a single migrated
 * character (design.md R19). Every test inside reads resolved state through
 * `window.__avatarHarness`, exactly as PR2/PR3/PR5 originally wrote them for `rasta` — this
 * function is a refactor of that original spec (tasks.md slice 21 task 4's approval-test
 * requirement), not new assertion logic.
 *
 * @param {string} character e.g. "rasta" — used only for readable test names and to locate that
 *   character's compiled accessory manifests on disk; the harness itself is driven by `avatarId`.
 * @param {number} avatarId `AvatarEnum` value for this character.
 * @param {object} [options]
 * @param {string|null} [options.hatKey] a compiled hat key this character owns (R10). `null` if
 *   the character has none — R10 is then skipped for this character, per tasks.md slice 21 task 9
 *   ("a character compiled but not yet screenshotted/covered must be listed as such").
 * @param {string|null} [options.petKey] a compiled pet key this character owns (R3/R4).
 * @param {string|null} [options.auraKey] a compiled aura key (R1/R2 both need one to be
 *   meaningful; R1/R2 still run without one, just without an aura child to assert on).
 * @param {number} [options.minResolvableKeys] R11's "the sweep covers a real number of keys"
 *   floor — differs per character's own compiled action-set size.
 * @param {'left'|'right'|null} [options.expectedPetSide] the pet's side, PINNED explicitly by
 *   this test-generation call rather than read back from the manifest it is meant to check
 *   (apply-progress.md "Correction 3", 2026-08-18): reading `petManifest.base.side` alone is
 *   self-referential and would pass even if `derivePetSide` regressed to a wrong answer, since
 *   the manifest would just as consistently agree with itself. Required whenever `petKey` is
 *   set — an explicit human decision per character, backed by the geometric evidence recorded
 *   in apply-progress.md for that character's pet package.
 * @param {string} [options.actionKey] the key `R8`/`R12` request via `playKey` to exercise a
 *   real action-pack-backed sequence — defaults to `'llorar'`, an ALIAS name every character
 *   compiled from a pre-existing baked `config.json` declares (`bakedKeyMap.cjs`'s derivation).
 *   A character compiled with NO baked precedent (slice 22: `sally`) has an EMPTY alias table
 *   (`compile-layered-avatar.cjs`'s own documented fact: "a character with no baked art... has
 *   none") — for such a character, pass the real sequence key directly (e.g. `'down_llorar'`),
 *   bypassing the missing alias layer entirely; R8/R12 only care that the key is real and
 *   action-pack-backed, not whether it is reached via an alias.
 * @param {string} [options.resolvedActionKey] the sequence key `actionKey` is expected to
 *   resolve to — defaults to `'down_llorar'` (rasta's own alias target). Equal to `actionKey`
 *   itself for a character with no alias layer.
 * @param {boolean} [options.emoteAliasWorks] whether the CRY EMOJI PRODUCT FEATURE
 *   (`playAction`, `UserEmojiAnimation.main`, hardcoded to request the literal string
 *   `'llorar'` for every character via `AvatarEmojisNameAnimationsEnum.CRY` — this is NOT
 *   parameterizable per character, unlike `actionKey` above) actually plays this character's
 *   crying pose. Defaults to `true`. A character with no `'llorar'` alias (again: `sally`) has
 *   this GENUINELY DEGRADE in the real game — pressing the cry emoji shows her idle pose, the
 *   same class of defect this whole change exists to fix, now surfacing for a DIFFERENT reason
 *   (no alias, not a broken action pipeline) on a character with no baked precedent. Set to
 *   `false` to skip R6's "the emote actually plays" assertions and instead assert the degrade
 *   is real, observable and correctly reported (never silent) — a disclosed product gap, not a
 *   test workaround.
 * @param {string} [options.animationUpdateTestKey] the key `R13` requests to prove
 *   `animationupdate`'s emitted key is the REQUESTED one, not a mirror-resolved source key.
 *   Defaults to `'right_walk'` (rasta's own mirror of `left_walk`). `LayeredAvatar.tick()` only
 *   emits `animationupdate` for a MULTI-FRAME resolved sequence (`_seqFrames.length > 1` —
 *   single-frame idle poses never tick), so this key must resolve to something with more than
 *   one frame. For a character with no mirrors at all (`sally`), `'right_walk'` degrades to the
 *   single-frame `down_idle` and the test would hang waiting for an event that structurally
 *   cannot fire — pass a real, directly-matching multi-frame key instead (e.g. `'down_walk'`);
 *   `_requestedKey` still equals whatever string is passed here regardless of resolution path,
 *   so the assertion remains meaningful even without going through a mirror.
 */
function describeCharacterMatrix(
  character,
  avatarId,
  {
    hatKey = null,
    petKey = null,
    auraKey = null,
    minResolvableKeys = 60,
    pixelCheckSlot = 'color1',
    pixelCheckColor = '#ff00ff',
    expectedPetSide = null,
    actionKey = 'llorar',
    resolvedActionKey = 'down_llorar',
    emoteAliasWorks = true,
    animationUpdateTestKey = 'right_walk',
  } = {}
) {
  if (petKey && expectedPetSide !== 'left' && expectedPetSide !== 'right') {
    throw new Error(
      `describeCharacterMatrix(${character}): petKey is set but expectedPetSide is not "left"/"right" — R3-pin requires an explicit, human-decided expectation (apply-progress.md Correction 3), not a value read back from the manifest under test.`
    )
  }

  test.describe(character, () => {
    const petManifest = petKey ? loadAccessoryManifest(character, 'pet', petKey) : null

    async function spawnCharacter(page, opts = {}) {
      const socketId = `${character}_${Date.now()}_${socketCounter++}`
      await page.evaluate(
        ({ socketId, opts, avatarId }) =>
          window.__avatarHarness.spawnAvatar({ socketId, avatarId, ...opts }),
        { socketId, opts, avatarId }
      )
      return socketId
    }

    async function readAfterDirection(page, socketId, direction) {
      return page.evaluate(
        ({ socketId, direction }) => {
          window.__avatarHarness.setDirection(socketId, direction)
          return window.__avatarHarness.readState(socketId)
        },
        { socketId, direction }
      )
    }

    test.beforeEach(async ({ page }) => {
      await page.goto('/harness.html')
      await page.waitForFunction(() => !!window.__avatarHarness)
    })

    test('R1: container child kind order and non-decreasing depth hold across all 8 directions', async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page, {
        accessories: { hat: hatKey ?? undefined, pet: petKey ?? undefined, aura: auraKey ?? undefined },
      })

      // Live-caught defect in THIS TEST (tasks.md slices 28-31, apply-progress.md): a single
      // static `expectedKinds` order, asserted unchanged across all 8 directions, silently
      // assumed a pet is uniformly "behind" (or uniformly "in front") for every character —
      // true for rasta (the only character this test ever ran against with a real accessory
      // until now) but NOT a general fact: `resolveAccessoryDepth('pet', {relativeY})` (design.md
      // §2) is a PER-FRAME decision, and measured live across the newly-compiled roster, several
      // characters' `pet09` genuinely SWITCHES between "behind" and "in front" by direction
      // (e.g. `brujita`: behind in 6 of 8 directions, front in `upright`/`upleft` — a real,
      // legitimate geometric fact of that character's own body/pet proportions, not a defect).
      // Rebuilt to assert the STRUCTURAL invariants that must hold regardless of which side a
      // per-direction pet lands on, rather than one hardcoded order: shadow first; nameBackground
      // then nameText last; the exact SET of kinds present matches configuration; body is always
      // before hat (hat's depth band 1.05-1.55 is always above body's 1.0, never direction- or
      // frame-dependent); and pet, if present, occupies EXACTLY one of its two legal depth slots
      // (fully behind body, or fully in front of hat/body and below aura) — never anything else.
      // The non-decreasing-depth loop below is UNCHANGED and is what actually proves the
      // resolved Phaser child order matches sorted depth, for any of these valid shapes.
      const expectedSet = new Set(['shadow', 'body', 'nameBackground', 'nameText'])
      if (hatKey) expectedSet.add('hat')
      if (petKey) expectedSet.add('pet')
      if (auraKey) expectedSet.add('aura')

      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        const kinds = state.children.map((c) => c.kind)

        expect(kinds[0], `direction ${direction}: shadow must be first`).toBe('shadow')
        expect(
          kinds.slice(-2),
          `direction ${direction}: name tag must be last, in order`
        ).toEqual(['nameBackground', 'nameText'])
        expect(new Set(kinds), `direction ${direction}: exact kind set`).toEqual(expectedSet)

        const bodyIdx = kinds.indexOf('body')
        if (hatKey) {
          expect(bodyIdx, `direction ${direction}: body before hat`).toBeLessThan(kinds.indexOf('hat'))
        }
        if (petKey) {
          const petIdx = kinds.indexOf('pet')
          const hatIdx = hatKey ? kinds.indexOf('hat') : -1
          const auraIdx = auraKey ? kinds.indexOf('aura') : -1
          const frontFloorIdx = hatIdx !== -1 ? hatIdx : bodyIdx
          const isBehind = petIdx < bodyIdx
          const isFront = petIdx > frontFloorIdx && (auraIdx === -1 || petIdx < auraIdx)
          expect(
            isBehind || isFront,
            `direction ${direction}: pet (index ${petIdx}) must be fully behind body (index ${bodyIdx}) or fully in front of hat/body and before aura — got kinds ${JSON.stringify(kinds)}`
          ).toBe(true)
        }

        const depths = state.children.map((c) => c.depth)
        for (let i = 1; i < depths.length; i++) {
          expect(depths[i], `direction ${direction}, child ${i}`).toBeGreaterThanOrEqual(
            depths[i - 1]
          )
        }
      }
    })

    test('R2: aura is resolved above both hat and body in every direction', async ({ page }) => {
      test.skip(!auraKey, `${character} has no compiled aura — R2 needs one to be meaningful`)
      const socketId = await spawnCharacter(page, {
        accessories: { hat: hatKey ?? undefined, pet: petKey ?? undefined, aura: auraKey },
      })

      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        const byKind = Object.fromEntries(state.children.map((c) => [c.kind, c]))

        if (hatKey) expect(byKind.aura.depth, `direction ${direction}`).toBeGreaterThan(byKind.hat.depth)
        expect(byKind.aura.depth, `direction ${direction}`).toBeGreaterThan(byKind.body.depth)

        // aura is last among the render-relevant accessory/body/shadow set (before the name tag)
        const renderOrder = ['shadow', 'pet', 'body', 'hat', 'aura']
        const auraIndex = state.children.findIndex((c) => c.kind === 'aura')
        const lastRelevantIndex = Math.max(
          ...renderOrder.map((kind) => state.children.findIndex((c) => c.kind === kind))
        )
        expect(auraIndex, `direction ${direction}`).toBe(lastRelevantIndex)
      }
    })

    test('R5: shadow stays at the local origin across all 8 directions', async ({ page }) => {
      const socketId = await spawnCharacter(page)

      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        const shadow = state.children.find((c) => c.kind === 'shadow')
        expect(shadow.x, `direction ${direction}`).toBe(0)
        expect(shadow.y, `direction ${direction}`).toBe(0)

        expect(
          Math.abs(state.body.visibleBounds.maxY),
          `direction ${direction}`
        ).toBeLessThanOrEqual(SHADOW_Y_BAND)
      }
    })

    test('R5-mirror: body centre-X is mirror-antisymmetric across every genuinely mirrored direction pair', async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page)
      const hasMirrors = await page.evaluate(
        (socketId) =>
          Object.keys(
            window.game.scene.getScenes(true)[0].users[socketId].spriteAvatar._manifest.mirrors || {}
          ).length > 0,
        socketId
      )
      // A character compiled with no baked-config precedent (sally: tasks.md slice 22) has an
      // EMPTY mirror table (`compile-layered-avatar.cjs`'s own documented fact) — `right`/
      // `rightdown`/`rightup` are never synthesized for her at all, so they degrade to `down`
      // (an UNRELATED pose, not a mirror), and antisymmetry against `left`/`leftdown`/`leftup`
      // is not a meaningful question to ask. This is the same disclosed gap R6-degrade/R13
      // already name for the alias/mirror-dependent surface — not re-derived here, just applied.
      test.skip(!hasMirrors, `${character} has no synthesized mirror directions to check`)

      const centerXByDirection = {}
      const stateByDirection = {}
      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        centerXByDirection[direction] = state.body.visibleBounds.centerX
        stateByDirection[direction] = state
      }

      // tasks.md slice 24 live finding: `down`/`up` map to THEMSELVES in `MIRROR_OF` (no
      // left-right counterpart exists to flip against — the comment on `MIRROR_OF` already
      // says so). Asserting `centerX(down) + centerX(down) <= tolerance` is therefore NOT a
      // mirror-mechanism check at all — it is a check that `down_idle`'s OWN art is
      // left-right-symmetric, an incidental property rasta/sally happen to have and brujita
      // (asymmetric hat decal), cholo (hair swept over one eye) and gata (asymmetric bushy
      // hair) do not — confirmed by contact sheet, not assumed (apply-progress.md). This loop's
      // own name is "every GENUINELY mirrored direction pair" — `down`/`up` are not one (there
      // is no separate source key being mirrored), so they are excluded here, restoring the
      // check to what it actually validates: real left/right-family antisymmetry.
      for (const direction of DIRECTIONS) {
        const mirror = MIRROR_OF[direction]
        if (mirror === direction) continue
        const sum = centerXByDirection[direction] + centerXByDirection[mirror]
        expect(Math.abs(sum), `direction ${direction} + ${mirror}`).toBeLessThanOrEqual(CENTER_X_TOL)
      }

      // BLOCKER fix (2026-08-18): the centre-X antisymmetry check above is necessary but NOT
      // sufficient — it can pass even when a right-family direction silently degrades to an
      // UNRELATED pose (e.g. a symmetric down_idle has centerX ~0, which trivially satisfies
      // "sum <= tolerance" against itself). This is exactly how sally shipped rendering only 5
      // of 8 directions while still passing R5-mirror (it was `test.skip`ped for her, but the
      // assertion itself carried no direct proof a mirror was ever actually taken). Tightened,
      // per character: every right-family direction must resolve to ITS OWN idle key (never a
      // different key, i.e. never silently degraded), report `mirrored: true`, and its
      // `sourceKey` must be exactly the left-family counterpart's idle key — the direct,
      // unambiguous proof design.md §5.5's mirror mechanism was actually exercised.
      for (const direction of RIGHT_FACING_DIRECTIONS) {
        const state = stateByDirection[direction]
        const expectedOwnKey = DIRECTION_TO_IDLE_KEY[direction]
        const expectedSourceKey = DIRECTION_TO_IDLE_KEY[MIRROR_OF[direction]]
        expect(state.body.sequenceKey, `direction ${direction} own key`).toBe(expectedOwnKey)
        expect(state.body.mirrored, `direction ${direction} mirrored flag`).toBe(true)
        expect(state.body.sourceKey, `direction ${direction} mirror source`).toBe(expectedSourceKey)
      }
    })

    test('R7: a completed non-repeating sequence emits animationcomplete and the real listener returns the avatar to idle', async ({
      page,
    }) => {
      // Not in design.md §10's original harness table — see avatarHarnessApi.js's `playChat`
      // docblock: every character's *_talk sequences are the only `repeat: 0` entries compiled
      // before the action pipeline lands, and UserChatAnimation.main is the real production
      // controller that both targets one and registers the one-time animationcomplete listener
      // R7 requires.
      const socketId = await spawnCharacter(page)

      const result = await page.evaluate(async (socketId) => {
        window.__avatarHarness.setDirection(socketId, 'down')
        await window.__avatarHarness.playChat(socketId, 'down_talk')
        const before = window.__avatarHarness.readState(socketId).body.sequenceKey

        // tasks.md slice 24 live finding: `down_talk`'s own frame count is NOT the same 8
        // frames across the roster (rasta/sally/empollon: 8; brujita/gata: 9; cholo: 12,
        // confirmed against each character's own compiled manifest) — a hardcoded "8" only
        // ever advanced far enough for rasta's/sally's/empollon's own coincidental frame count
        // and undershot the real duration for the other three, leaving `down_talk` still
        // playing rather than completed. Read the REAL frame count from the manifest this
        // character actually compiled, instead of assuming it.
        const scene = window.game.scene.getScenes(true)[0]
        const frameCount = scene.users[socketId].spriteAvatar._manifest.sequences.down_talk.frames.length
        window.__avatarHarness.advance(Math.ceil((frameCount / 19) * 1000) + 1)
        const after = window.__avatarHarness.readState(socketId).body.sequenceKey
        return { before, after }
      }, socketId)

      expect(result.before).toBe('down_talk')
      expect(result.after).toBe('down_idle')
    })

    test('R9: playKey for a body-uncovered key degrades observably with requestedKey/resolvedKey/reason', async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page)

      const degrades = await page.evaluate((socketId) => {
        window.__avatarHarness.setDirection(socketId, 'left')
        // Deliberately fictional — never a real sequences/aliases/mirrors key on any character.
        window.__avatarHarness.playKey(socketId, 'left_moonwalk_9000')
        return window.__avatarHarness.degrades()
      }, socketId)

      const match = degrades.find((d) => d.requestedKey === 'left_moonwalk_9000')
      expect(match).toBeTruthy()
      expect(match.resolvedKey).toBe('left_idle')
      expect(match.reason).toBe('direction-idle')
    })

    test('R6: triggering CRY (playAction, the real UserEmojiAnimation.main path) visibly changes from idle via the "llorar" emote alias', async ({
      page,
    }) => {
      test.skip(
        !emoteAliasWorks,
        `${character} has no "llorar" alias (no baked-config precedent to derive it from) — the CRY emoji product feature genuinely degrades to idle for this character; see the dedicated degrade-is-observable test below instead`
      )
      const socketId = await spawnCharacter(page)

      // design.md §13.3 (tasks.md slice 15): the always-on prefetch is REMOVED — nothing loads
      // an action pack until `play()` first resolves a key backed by one. Capture the real idle
      // state, trigger (which starts the real, reactive load for the resolved llorar pack),
      // THEN wait for that SPECIFIC pack. `resolvedActionKey` (not a hardcoded 'down_llorar')
      // is what this character's own "llorar" alias actually resolves to (tasks.md slice 25
      // live finding: marsu's resolves to 'leftdown_llorar' — a hardcoded 'down_llorar' here
      // would wait forever for a pack that character never requests).
      const idleSeqKey = await page.evaluate((socketId) => {
        window.__avatarHarness.setDirection(socketId, 'down')
        return window.__avatarHarness.readState(socketId).body.sequenceKey
      }, socketId)
      await page.evaluate(
        ({ socketId, cryEmojiId }) => {
          window.__avatarHarness.playAction(socketId, cryEmojiId)
        },
        { socketId, cryEmojiId: CRY_EMOJI_ID }
      )
      await page.waitForFunction(
        ({ id, key }) =>
          window.game.scene.getScenes(true)[0].users[id].spriteAvatar._atlasKeys.actions.has(key),
        { id: socketId, key: resolvedActionKey }
      )

      const result = await page.evaluate(({ socketId }) => {
        const beforeAdvance = window.__avatarHarness.readState(socketId)
        window.__avatarHarness.advance(200)
        const afterAdvance = window.__avatarHarness.readState(socketId)
        return {
          resolvedSeqKey: beforeAdvance.body.sequenceKey,
          requestedKey: beforeAdvance.body.requestedKey,
          seqIndexBefore: beforeAdvance.body.seqIndex,
          seqIndexAfter: afterAdvance.body.seqIndex,
        }
      }, { socketId })

      expect(idleSeqKey).toBe('down_idle')
      expect(result.resolvedSeqKey).toBe(resolvedActionKey)
      expect(result.requestedKey).toBe('llorar')
      expect(result.seqIndexAfter).not.toBe(result.seqIndexBefore)
    })

    test('R6-degrade: for a character with no "llorar" alias, the CRY emoji degrades OBSERVABLY to idle, never silently (disclosed product gap)', async ({
      page,
    }) => {
      test.skip(emoteAliasWorks, `${character} has a real "llorar" alias — R6 above covers it`)
      const socketId = await spawnCharacter(page)

      const result = await page.evaluate(
        async ({ socketId, cryEmojiId }) => {
          window.__avatarHarness.setDirection(socketId, 'down')
          await window.__avatarHarness.playAction(socketId, cryEmojiId)
          const state = window.__avatarHarness.readState(socketId)
          const degrades = window.__avatarHarness.degrades()
          return {
            sequenceKey: state.body.sequenceKey,
            requestedKey: state.body.requestedKey,
            degrade: degrades.find((d) => d.requestedKey === 'llorar'),
          }
        },
        { socketId, cryEmojiId: CRY_EMOJI_ID }
      )

      // The honest, real behaviour: no crash, no silent no-op — the avatar visibly stays on
      // down_idle and the substitution is reported via degradeReporter, exactly like every
      // other degrade this whole change makes observable (design.md §9). This is NOT the same
      // bug the proposal's original report describes (the action pipeline itself works —
      // `down_llorar` IS a real, compiled, action-pack-backed sequence for this character, see
      // the R8/R12 assertions above using it directly) — it is a narrower, disclosed gap: the
      // generic CRY->'llorar' emoji binding has no matching alias for a character with no baked
      // precedent.
      expect(result.requestedKey).toBe('llorar')
      expect(result.sequenceKey).toBe('down_idle')
      expect(result.degrade, 'degradeReporter must have recorded this substitution').toBeTruthy()
      expect(result.degrade.resolvedKey).toBe('down_idle')
      expect(result.degrade.reason).toBe('down-idle')
    })

    test("R8: the player's custom palette survives an entire action sequence (frame 0, mid, last)", async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page, { palette: { [pixelCheckSlot]: pixelCheckColor } })
      const manifestHasSlot = await page.evaluate(
        ({ socketId, slot }) =>
          // Correction 2 (apply-progress.md, 2026-08-18): checking `defaults` alone conflates
          // "no manifest default value" with "no palette slot at all" — `computeManifestSlots`'s
          // union (tasks.md slice 26 defect 2) means a character with an empty vector colormeta
          // (ninja/werewolf/skeleton/zombie) can still have a REAL piece-referenced slot in
          // `manifest.slots` that `resolvePalette` (which iterates `manifest.slots`, not
          // `defaults`) honours. `manifest.slots` is the correct membership check.
          window.game.scene.getScenes(true)[0].users[socketId].spriteAvatar._manifest.slots.includes(slot),
        { socketId, slot: pixelCheckSlot }
      )
      test.skip(!manifestHasSlot, `${character}'s manifest has no "${pixelCheckSlot}" slot`)
      const EXPECTED_TINT = parseInt(pixelCheckColor.replace('#', ''), 16)

      await page.evaluate(
        ({ socketId, actionKey }) => {
          window.__avatarHarness.setDirection(socketId, 'down')
          window.__avatarHarness.playKey(socketId, actionKey)
        },
        { socketId, actionKey }
      )
      await page.waitForFunction(
        ({ id, resolvedActionKey }) =>
          window.game.scene.getScenes(true)[0].users[id].spriteAvatar._atlasKeys.actions.has(
            resolvedActionKey
          ),
        { id: socketId, resolvedActionKey }
      )

      const result = await page.evaluate(({ socketId, slot }) => {
        const sampleColor1Tints = () =>
          window.__avatarHarness
            .readState(socketId)
            .body.slotTints.filter((t) => t.slot === slot)
            .map((t) => t.tint)

        const frame0 = sampleColor1Tints()
        window.__avatarHarness.advance(200)
        const frameMid = sampleColor1Tints()
        window.__avatarHarness.advance(2000)
        const frameLast = sampleColor1Tints()

        return { frame0, frameMid, frameLast }
      }, { socketId, slot: pixelCheckSlot })

      // tasks.md slice 26 live finding: `boomer`'s own `down_llorar` frame 0 (hands raised to
      // the face at the very start of the pose, confirmed by direct probe against the real
      // manifest, not assumed) has ZERO visible `color1`-slotted pieces at all — a real,
      // disclosed fact of THIS character's specific action art (the same class of per-frame
      // occlusion the slice-25 contact-sheet review already found for `modern`'s own
      // `down_llorar`), not a tinting defect. Requiring a non-empty tint list at EVERY one of
      // the 3 sampled instants is therefore too strict for the whole roster: it conflates "the
      // slot never renders here" (a legitimate per-frame occlusion) with "tinting silently
      // failed" (the real defect this test exists to catch). Relaxed to what the test's own
      // name actually promises — "survives an ENTIRE action sequence" — every tint value found
      // at ANY of the 3 samples must still be exactly correct (never silently wrong, at any
      // sample), and at least ONE of the 3 samples must show a real tinted piece (proving
      // tinting genuinely happened somewhere across the sequence, not that it never happened at
      // all).
      const allTints = [...result.frame0, ...result.frameMid, ...result.frameLast]
      expect(
        allTints.length,
        'at least one of frame0/frameMid/frameLast must show a real tinted "' + pixelCheckSlot + '" piece'
      ).toBeGreaterThan(0)
      for (const [label, tints] of Object.entries(result)) {
        for (const tint of tints) {
          expect(tint, label).toBe(EXPECTED_TINT)
        }
      }
    })

    test('R8-pixel: the ACTUAL RENDERED PIXEL colour of a body slot matches the resolved palette, not merely the logical child.tint property', async ({
      page,
    }) => {
      // Coordinator-flagged defect (recorded in apply-progress.md): every prior assertion in
      // this file that checks a colour reads `child.tint` (a Phaser Sprite property Phaser
      // updates the moment `setTint()` is called), which is exactly the wiring-not-outcome gap
      // design.md §19 risk 18 names. `child.tint` is set correctly REGARDLESS of whether the
      // active renderer ever draws it — confirmed live: under `Phaser.CANVAS`, `setTint()`
      // updated `.tint` to the resolved colour while the actual rendered pixel stayed pure
      // white, because `Phaser.Renderer.Canvas.CanvasRenderer#batchSprite` draws every sprite
      // via a plain `ctx.drawImage(...)` with no tint handling at all. This test reads a REAL
      // screenshot pixel instead, so it fails exactly where every `.tint`-only assertion above
      // (including R8 itself) did not.
      const socketId = await spawnCharacter(page, {
        // {x:5, y:5} tile position (same trick `buildAvatarContactSheet.js` documents): the
        // numeric matrix's default {x:0, y:0} spawn renders with its feet at the very top edge
        // of the canvas, entirely off-screen — harmless for every OTHER test above, which reads
        // resolved logical state only, but this is the first test in this file that needs the
        // avatar to be actually ON the visible canvas to sample a real pixel from it.
        x: 5,
        y: 5,
        palette: { [pixelCheckSlot]: pixelCheckColor },
      })

      const manifestHasSlot = await page.evaluate(
        ({ socketId, slot }) =>
          // Correction 2 (apply-progress.md, 2026-08-18): checking `defaults` alone conflates
          // "no manifest default value" with "no palette slot at all" — `computeManifestSlots`'s
          // union (tasks.md slice 26 defect 2) means a character with an empty vector colormeta
          // (ninja/werewolf/skeleton/zombie) can still have a REAL piece-referenced slot in
          // `manifest.slots` that `resolvePalette` (which iterates `manifest.slots`, not
          // `defaults`) honours. `manifest.slots` is the correct membership check.
          window.game.scene.getScenes(true)[0].users[socketId].spriteAvatar._manifest.slots.includes(slot),
        { socketId, slot: pixelCheckSlot }
      )
      test.skip(!manifestHasSlot, `${character}'s manifest has no "${pixelCheckSlot}" slot`)

      const rect = await page.evaluate(
        ({ socketId, slot }) => {
          window.__avatarHarness.setDirection(socketId, 'down')
          const scene = window.game.scene.getScenes(true)[0]
          const avatar = scene.users[socketId].spriteAvatar
          const candidates = avatar._pool.filter((child) => {
            if (!child.visible) return false
            const pieceId = child.getData('pieceId')
            const manifestPiece = pieceId && avatar._manifest.pieces[pieceId]
            return manifestPiece && manifestPiece.slot === slot
          })
          if (candidates.length === 0) return null
          // Live-discovered (tasks.md slice 21 defect-1 fix): a slotted run's bounding box is
          // NOT necessarily uniformly filled — the FIRST match can be a small, irregularly
          // shaped run (an eyebrow, a fingernail) whose geometric centre lands on a
          // partially-transparent/anti-aliased pixel, blending with whatever sits behind it and
          // producing a flaky, non-representative sample. The LARGEST-by-area candidate (e.g.
          // rasta's own face/torso run) is overwhelmingly likely to have a solid, uniformly
          // coloured interior at its own centre.
          const biggest = candidates.reduce((best, child) => {
            const b = child.getBounds()
            const area = b.width * b.height
            return !best || area > best.area ? { child, area, bounds: b } : best
          }, null)
          const bounds = biggest.bounds
          const canvasRect = document.querySelector('canvas').getBoundingClientRect()
          return {
            // page-space clip: the piece's own world-space bounds (== canvas-local, this
            // harness's camera never scrolls) offset by the canvas element's own page position.
            x: canvasRect.left + bounds.left,
            y: canvasRect.top + bounds.top,
            width: bounds.width,
            height: bounds.height,
          }
        },
        { socketId, slot: pixelCheckSlot }
      )
      expect(rect, `${character} has a visible "${pixelCheckSlot}"-slotted piece`).toBeTruthy()

      // Real paint wait (matching avatar-contact-sheet.spec.js's own documented need) — this is
      // the first assertion in THIS file that reads an actual rendered pixel, not resolved
      // logical state.
      await page.waitForTimeout(100)

      // Sample a small patch well inside the piece's own bounds (avoids anti-aliased edge
      // pixels, which legitimately blend with whatever sits behind them).
      const maxSampleSize = Math.max(2, Math.min(8, Math.floor(Math.min(rect.width, rect.height) / 2)))

      // tasks.md slice 24 live finding: the geometric bbox CENTRE of "the biggest same-slot
      // run" is not reliably interior-filled across the roster the way it is for rasta/sally/
      // cholo — brujita's biggest `color1` ("piel") run's bbox centre lands under her hat brim
      // (sampled near-black, not skin), and empollon's/gata's land in the transparent gap
      // between two disjoint skin regions the run's own bbox spans (both hands, or face+neck
      // with a gap) — confirmed live via direct pixel probes, not assumed. The run's bbox is
      // still the right SEARCH AREA (design.md's own "largest run" heuristic remains correct:
      // it is overwhelmingly likely to CONTAIN a solid interior patch somewhere), but the exact
      // centre is not reliably THAT patch for every character's art. Search a small, fixed grid
      // of candidate points across the run's own bbox (never expanding the search outside it)
      // and keep the SINGLE candidate with the lowest differing fraction — this still requires
      // one genuine solid-coloured match against the resolved palette (the real defect this
      // test exists to catch, 100% differing, fails at every candidate identically), it just
      // stops assuming the bbox centre is always that match.
      //
      // tasks.md slice 26 live finding: `yayo`'s own biggest `color1` run is a genuinely
      // NARROW visible strip (the nose bridge between two large sunglasses lenses — most of
      // the run's own bbox is covered by the sunglasses/moustache pieces drawn on top, both
      // unrelated to `color1`) — narrower than an 8x8 patch anywhere within it, so even the
      // best of the 25 fixed-size candidates above still straddled the sunglasses' dark rim.
      // Shrinking the sample size (4x4, then 2x2) over the SAME grid, only once the largest
      // size fails to find a clean match, finds a genuinely interior point without widening the
      // search area or lowering the match threshold.
      const CANDIDATE_FRACTIONS = [0.2, 0.35, 0.5, 0.65, 0.8]
      let best = null
      sizes: for (const sampleSize of [maxSampleSize, 4, 2]) {
        if (sampleSize > maxSampleSize) continue
        for (const yFraction of CANDIDATE_FRACTIONS) {
          for (const xFraction of CANDIDATE_FRACTIONS) {
            const clip = {
              x: Math.round(rect.x + rect.width * xFraction - sampleSize / 2),
              y: Math.round(rect.y + rect.height * yFraction - sampleSize / 2),
              width: sampleSize,
              height: sampleSize,
            }
            const screenshotBuffer = await page.screenshot({ clip })
            // `.ensureAlpha()`: a Playwright screenshot PNG has no alpha channel (opaque
            // background), so a raw decode without it is 3-channel RGB — `diffRgbaBuffers`
            // requires 4 (RGBA), the same shape `buildSolidRgbaBuffer` always produces.
            const { data: sampledRgba } = await sharp(screenshotBuffer)
              .ensureAlpha()
              .raw()
              .toBuffer({ resolveWithObject: true })

            const expectedRgba = buildSolidRgbaBuffer(sampleSize, sampleSize, pixelCheckColor)
            // Reuses the already-tested R16/R17b comparator (shared/assetPipeline/compareRasters.js)
            // rather than writing a second pixel-diff routine. Tolerance 40 per channel: generous
            // enough for WebGL compositing/anti-aliasing rounding on a real screenshot, nowhere
            // near enough to let a pure-white (255,255,255) rendered patch pass against a
            // resolved skin/costume colour — every one of rasta's own `colormeta.defaults`
            // values differs from white by well over 100 on at least one channel (e.g. color1
            // `b88a5c`: |0xb8-0xff|=71).
            const { differingPixels, totalPixels } = diffRgbaBuffers(
              new Uint8ClampedArray(sampledRgba),
              expectedRgba,
              sampleSize,
              sampleSize,
              { tolerance: 40 }
            )
            const differingFraction = differingPixels / totalPixels
            if (!best || differingFraction < best.differingFraction) {
              best = { differingFraction, totalPixels, xFraction, yFraction, sampleSize }
            }
            if (differingFraction === 0) break sizes // already found a perfect interior match
          }
        }
        if (best && best.differingFraction <= 0.1) break // good enough at this size already
      }

      // Live-discovered (tasks.md slice 21 defect-1 fix): even the LARGEST slotted run is not
      // a perfect rectangle at pixel scale — a handful of pixels at the very centre-row/column
      // of an 8x8 sample can still land on a genuinely anti-aliased sub-pixel edge (confirmed:
      // 5/64 differing pixels on rasta's own biggest color1 run, all consistent with edge
      // blending, none anywhere close to the 64/64-differing signature the real CANVAS-renderer
      // defect produced). A MAJORITY threshold (≥90% of the BEST candidate sample must match) is
      // what actually distinguishes "correctly tinted, minor edge anti-aliasing" from "not
      // tinted at all" — asserting a literal 0 here would be exact-pixel-baseline brittleness of
      // the kind this change deliberately rejected elsewhere (design.md's own resolved-state-
      // over-baseline choice), while a majority-match threshold still fails hard against the
      // real defect (which produced 100% differing at EVERY candidate point, not a handful of
      // edge pixels at only one of them).
      expect(
        best.differingFraction,
        `no candidate patch (sizes up to ${maxSampleSize}x${maxSampleSize}, ${CANDIDATE_FRACTIONS.length}x${CANDIDATE_FRACTIONS.length} grid each) at a "${pixelCheckSlot}" piece rendered close to ${pixelCheckColor} (best: ${best.differingFraction} at ${best.sampleSize}x${best.sampleSize})`
      ).toBeLessThanOrEqual(0.1)
      expect(best.totalPixels).toBe(best.sampleSize * best.sampleSize)
    })

    test('R11: every key in sequences ∪ aliases ∪ mirrors resolves to itself with degraded === false (full action-coverage sweep)', async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page)

      await page.evaluate((socketId) => window.__avatarHarness.preloadActionPacks(socketId), socketId)

      const result = await page.evaluate((socketId) => {
        const scene = window.game.scene.getScenes(true)[0]
        const manifest = scene.users[socketId].spriteAvatar._manifest
        const allKeys = [
          ...Object.keys(manifest.sequences),
          ...Object.keys(manifest.aliases),
          ...Object.keys(manifest.mirrors),
        ]

        const mismatches = []
        for (const key of allKeys) {
          window.__avatarHarness.playKey(socketId, key)
          window.__avatarHarness.advance(1)
          const state = window.__avatarHarness.readState(socketId)
          if (state.body.requestedKey !== key) {
            mismatches.push({ key, actual: state.body.requestedKey })
          }
        }

        return { totalKeys: allKeys.length, mismatches, degrades: window.__avatarHarness.degrades() }
      }, socketId)

      expect(result.totalKeys).toBeGreaterThan(minResolvableKeys)
      expect(result.mismatches).toEqual([])
      const nonSpawnDegrades = result.degrades.filter((d) => d.requestedKey !== 'undefined')
      expect(nonSpawnDegrades).toEqual([])
    })

    test('R12: a lazy action-pack key degrades observably (pack-loading) before the load completes, then resolves to the real sequence once it arrives', async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page)

      const immediateResult = await page.evaluate(
        ({ socketId, actionKey }) => {
          window.__avatarHarness.setDirection(socketId, 'down')
          window.__avatarHarness.playKey(socketId, actionKey)
          const state = window.__avatarHarness.readState(socketId)
          const degrades = window.__avatarHarness.degrades()
          return {
            sequenceKeyImmediatelyAfter: state.body.sequenceKey,
            packLoadingDegrade: degrades.find(
              (d) => d.requestedKey === actionKey && d.reason === 'pack-loading'
            ),
          }
        },
        { socketId, actionKey }
      )

      expect(immediateResult.sequenceKeyImmediatelyAfter).toBe('down_idle')
      expect(immediateResult.packLoadingDegrade).toBeTruthy()
      expect(immediateResult.packLoadingDegrade.resolvedKey).toBe('down_idle')

      await page.waitForFunction(
        ({ id, resolvedActionKey }) =>
          window.game.scene.getScenes(true)[0].users[id].spriteAvatar._atlasKeys.actions.has(
            resolvedActionKey
          ),
        { id: socketId, resolvedActionKey }
      )
      const afterLoad = await page.evaluate(
        (socketId) => window.__avatarHarness.readState(socketId).body.sequenceKey,
        socketId
      )
      expect(afterLoad).toBe(resolvedActionKey)
    })

    test('R13: animationupdate carries the REQUESTED key, not the mirror-resolved source key, with a 1-based frame index', async ({
      page,
    }) => {
      const socketId = await spawnCharacter(page)

      const captured = await page.evaluate(
        ({ socketId, testKey }) =>
          new Promise((resolve) => {
            const scene = window.game.scene.getScenes(true)[0]
            const user = scene.users[socketId]
            user.spriteAvatar.once('animationupdate', (anim, frame) => {
              resolve({ key: anim.key, index: frame.index })
            })
            window.__avatarHarness.playKey(socketId, testKey)
            window.__avatarHarness.advance(200)
          }),
        { socketId, testKey: animationUpdateTestKey }
      )

      expect(captured.key).toBe(`${avatarId}_${animationUpdateTestKey}`)
      expect(Number.isInteger(captured.index)).toBe(true)
      expect(captured.index).toBeGreaterThanOrEqual(1)
    })

    test('R3: the pet stays on its manifest-declared canonical side across all 8 directions', async ({
      page,
    }) => {
      test.skip(!petKey, `${character} has no compiled pet — R3 does not apply`)
      // Correction 3 pin: the manifest's OWN declared side must match the explicit, externally-
      // decided expectation, not just be internally consistent with itself.
      expect(petManifest.base.side, `${character}'s compiled pet manifest`).toBe(expectedPetSide)
      const socketId = await spawnCharacter(page, { accessories: { pet: petKey } })

      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        const pet = state.children.find((c) => c.kind === 'pet')
        const halfWidth = pet.displayWidth / 2
        const { maxX, minX } = state.body.visibleBounds

        // R3-pin: assert against `expectedPetSide` (the pinned, human-decided value), not
        // `petManifest.base.side` — a self-referential comparison would trivially pass even if
        // the derivation regressed, since the manifest would agree with itself either way.
        if (expectedPetSide === 'right') {
          expect(pet.x - halfWidth, `direction ${direction}`).toBeGreaterThanOrEqual(
            maxX - CENTER_X_TOL
          )
        } else {
          expect(pet.x + halfWidth, `direction ${direction}`).toBeLessThanOrEqual(
            minX + CENTER_X_TOL
          )
        }
      }
    })

    test('R4: the pet only flips flipX to face the current direction; its resolved x sign never crosses sides', async ({
      page,
    }) => {
      test.skip(!petKey, `${character} has no compiled pet — R4 does not apply`)
      const socketId = await spawnCharacter(page, { accessories: { pet: petKey } })
      const xSigns = []
      const expectedSign = expectedPetSide === 'right' ? 1 : -1

      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        const pet = state.children.find((c) => c.kind === 'pet')

        expect(pet.flipX, `direction ${direction}`).toBe(RIGHT_FACING_DIRECTIONS.has(direction))
        // R4-pin: the resolved x sign must match `expectedPetSide` in EVERY direction, not
        // merely agree with itself across directions — a fixed-but-wrong side would still pass
        // the old "at most one distinct sign" check below.
        expect(Math.sign(pet.x), `direction ${direction}`).toBe(expectedSign)
        xSigns.push(Math.sign(pet.x))
      }

      const nonZeroSigns = xSigns.filter((s) => s !== 0)
      expect(new Set(nonZeroSigns).size, `signs seen: ${xSigns.join(',')}`).toBeLessThanOrEqual(1)
    })

    test('R10: the hat resolves to a real, finite, above-body position for this character', async ({
      page,
    }) => {
      test.skip(!hatKey, `${character} has no compiled hat — R10 does not apply`)
      const socketId = await spawnCharacter(page, { accessories: { hat: hatKey } })

      for (const direction of DIRECTIONS) {
        const state = await readAfterDirection(page, socketId, direction)
        const hat = state.children.find((c) => c.kind === 'hat')

        expect(hat, `direction ${direction}`).toBeTruthy()
        expect(hat.visible, `direction ${direction}`).toBe(true)
        expect(Number.isFinite(hat.x), `direction ${direction}`).toBe(true)
        expect(Number.isFinite(hat.y), `direction ${direction}`).toBe(true)
        // resolved above the body (design.md §2's hat depth band, 1.05-1.55)
        expect(hat.depth, `direction ${direction}`).toBeGreaterThan(1.0)
        expect(hat.depth, `direction ${direction}`).toBeLessThan(1.6)
      }
    })
  })
}

// tasks.md slice 21 task 4 (approval test): rasta's own 13 R-ids run through this parameterized
// generator with the SAME options as before parameterization (minnieHat/pet09/auraElectrica) —
// identical pass/fail outcome to the pre-slice-21 hardcoded spec. AvatarEnum.RASTA === 12.
describeCharacterMatrix('rasta', 12, {
  hatKey: 'minnieHat',
  petKey: 'pet09',
  auraKey: 'auraElectrica',
  minResolvableKeys: 60,
  // apply-progress.md "Correction 3" (2026-08-18): pet09's own raw source geometry places it
  // firmly RIGHT of the body for both `down_idle` (+18.67 logical units) and `up_idle` (+16.76)
  // — its only two facing directions that can never be mirrored, so their side is fixed by the
  // art regardless of any derivation. `left`-family poses naturally sit left, but per the
  // locked design decision (proposal.md item 2) the pet holds ONE side across all 8 directions.
  expectedPetSide: 'right',
})

// tasks.md slice 22 + BLOCKER fix (2026-08-18): sally (AvatarEnum.SALLY === 18) — no hat/pet/
// aura (design.md §16: absent from the accessory roster). `minResolvableKeys: 40` — her real
// compiled total is now 63 (41 sequences + 22 convention-derived mirrors, up from the original
// 41/0/0 sequences/aliases/mirrors this character shipped with). She has NO pre-existing baked
// `config.json` for `bakedKeyMap.cjs`'s NORMAL derivation to read (a fact the compiler's own
// `readBakedKeyMap` docblock already names: "a character with no baked art, e.g. sally... has
// none") — but every `.layers.bb` in the asset set ships only left-family source art and encodes
// "right mirrors left" as a universal convention independent of any baked precedent, so
// `bakedKeyMap.cjs`'s `deriveConventionMirrors` fallback now derives her 22 mirrors directly
// from her own compiled sequence names. This fixed the reported blocker: sally previously
// rendered the SAME front-facing pose for down/downright/right/upright (5 of 8 directions, not
// 8) — she now renders all 8 as distinct, correct poses (confirmed in her regenerated contact
// sheet, and by R5-mirror's tightened per-direction resolvedKey/mirrored/sourceKey assertions
// below, which now run for real instead of being `test.skip`ped).
// Two remaining, disclosed consequences of having zero ALIASES (a fact independent of mirrors —
// no baked config also means no short emote-name-to-sequence mapping):
//   1. `emoteAliasWorks: false` — the CRY emoji product feature (hardcoded to request the
//      literal 'llorar', not parameterizable per character) has no alias to resolve through for
//      sally and genuinely degrades to her idle pose; R6-degrade (not R6) covers this character.
//   2. `actionKey`/`resolvedActionKey: 'down_llorar'` — R8/R12 call the REAL sequence key
//      directly, bypassing the missing alias layer (the alias mechanism, not the action
//      pipeline itself, is what is missing — `down_llorar` IS a real, compiled,
//      action-pack-backed sequence for sally, confirmed by R12 passing against it directly).
// No `pixelCheckSlot`/palette override is set: sally's `colormeta.defaults` is genuinely EMPTY
// (0 slots, not merely sparse — verified directly against her vector `sally.bb`'s own
// `meta.json.colormeta` this slice, which reports `{defaults:{}, labels:{}}` — she is genuinely
// the only roster character with zero recolourable slots, not a compiler defect), so R8 and
// R8-pixel both `test.skip` cleanly via their existing "manifest has no such slot" guard.
describeCharacterMatrix('sally', 18, {
  minResolvableKeys: 62,
  actionKey: 'down_llorar',
  resolvedActionKey: 'down_llorar',
  emoteAliasWorks: false,
  // Kept unchanged from slice 22, not re-verified against the now-fixed default: R13's default
  // ('right_walk') would now resolve as a real mirror (from left_walk, 13 frames, per the
  // compiler's own logged mirror table) rather than degrading, so the override is no longer
  // strictly required — left in place deliberately (lowest-risk choice for this fix) since
  // 'down_walk' is an equally valid, real, directly-matching multi-frame sequence for R13's
  // "requestedKey stays the requested string" assertion.
  animationUpdateTestKey: 'down_walk',
})

// tasks.md slice 24 (design.md §15's slice 23) — body batch 1: brujita, cholo, empollon, gata.
// Body-only compiles (this batch's own scope per tasks.md slices 24-27: "accessories, if any,
// compile in slices 28-31") — no hatKey/petKey/auraKey for any of the four, same as sally's own
// no-accessory shape. Unlike sally, all four DO have a real, pre-existing baked `config.json`
// (`bommer`'s siblings — the roster's original, un-migrated legacy characters), so
// `bakedKeyMap.cjs`'s NORMAL `deriveAliasesAndMirrors` path applies (real precedent, not the
// convention-mirror fallback sally/future vector-only characters need): every one of the four
// resolves the default `actionKey: 'llorar'` -> `resolvedActionKey: 'down_llorar'` alias exactly
// like rasta, so neither is overridden below. All four also carry a real `color1` palette slot
// (verified against each character's own compiled manifest, not assumed), so the default
// `pixelCheckSlot: 'color1'` is left at its default rather than skipped. `minResolvableKeys` is
// each character's own real (sequences + aliases + mirrors) total, minus a small margin
// (rasta's own precedent: real 65, floor 60), never the raw total itself — R11 asserts
// `toBeGreaterThan(minResolvableKeys)`, so the floor must sit strictly below the real count.
//
// tasks.md slices 28-30 (accessory batches): every one of these 12 characters now has all 36
// on-disk accessory packages (26 hats + 10 pets) compiled — `hatKey: 'minnieHat'`/
// `petKey: 'pet09'` chosen uniformly across the whole roster (present under every character,
// confirmed against the source dump) for R10/R3/R4 coverage. `expectedPetSide: 'right'` is
// PINNED the same way rasta's own is (not read back from the manifest under test) — backed by
// real geometric evidence: `compile-accessory.cjs`'s own `derivePetSide` printed "right" for
// EVERY one of 150 real derivations (15 characters × 10 pets each, apply-progress.md), a
// unanimous real measurement, not an assumption carried over from rasta.
describeCharacterMatrix('brujita', 2, {
  minResolvableKeys: 58,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('cholo', 3, {
  minResolvableKeys: 60,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('empollon', 4, {
  minResolvableKeys: 60,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('gata', 5, {
  minResolvableKeys: 58,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})

// tasks.md slice 25 (design.md §15's slice 24) — body batch 2: india, lilian, marsu, modern.
// Same body-only shape as slice 24. All four have a real baked-config `llorar` alias — but it
// resolves to a DIFFERENT real sequence per character (verified against each character's own
// compiled manifest, not assumed): india/lilian/modern resolve to `down_llorar` (left at the
// default), but marsu's resolves to `leftdown_llorar` (down_llorar is not one of marsu's 41
// compiled sequences at all — her crying pose was only ever authored facing leftdown) —
// overridden explicitly below. `lilian`'s `Custom6Hat` compiling in slice 29 is what completes
// R10 pairwise (vs `rasta`'s own `Custom6Hat`) — both now covered here via `minnieHat` for the
// uniform per-character matrix, with the pairwise `Custom6Hat` comparison itself recorded in
// apply-progress.md (measure-accessory-overlap.cjs), not duplicated as a second matrix entry.
describeCharacterMatrix('india', 7, {
  minResolvableKeys: 60,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('lilian', 8, {
  minResolvableKeys: 60,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('marsu', 9, {
  minResolvableKeys: 59,
  actionKey: 'llorar',
  resolvedActionKey: 'leftdown_llorar',
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('modern', 10, {
  minResolvableKeys: 58,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})

// tasks.md slice 26 (design.md §15's slice 25) — body batch 3: ninja, werewolf, yayo, boomer.
// `boomer` compiles from `bommer.layers.bb` via the existing srcName lookup table (§4) —
// `manifest.character === "boomer"` confirmed, no compiler change needed. Live-caught data fact:
// `ninja` and `werewolf` both have a genuinely EMPTY vector `colormeta` at the source (verified
// directly against each character's own vector `.bb`'s `meta.json.colormeta`:
// `{"defaults":{},"labels":{},"creatorIdx":0}` for both) — the second and third roster
// characters after `sally` with zero DECLARED palette slots, not a compiler defect.
//
// Correction 2 (apply-progress.md, 2026-08-18): an earlier pass's comment here (and this file's
// own R8/R8-pixel guard) wrongly conflated "no manifest DEFAULT" with "no palette slot at all"
// and skipped both tests for ninja/werewolf. `computeManifestSlots`'s union (slice 26 defect 2)
// means both characters DO have real piece-referenced slots in `manifest.slots`
// (`['color3','color1','color2','color4','colorGuante']` for ninja, verified directly against
// the compiled manifest) that `resolvePalette` honours even with no default — the fix DID reach
// the manifest; only the test guard (and the contact-sheet config below) had not caught up. The
// guard now checks `manifest.slots.includes(slot)`, and the default `pixelCheckSlot: 'color1'` is
// left un-overridden for both — R8/R8-pixel now run for real and pass (verified live: 8/8 passed
// across ninja/werewolf/skeleton/zombie after the guard fix, 0 skipped). `boomer`'s own accessory
// packages self-declare `meta.char: "bommer"` (the source archive's own name, not the client
// name) — a live-caught defect (`resolveSourceCharName`, apply-progress.md) fixed at compile time
// so the registry/matrix below need no special case for this character.
describeCharacterMatrix('ninja', 11, {
  minResolvableKeys: 61,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('werewolf', 14, {
  minResolvableKeys: 57,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('yayo', 16, {
  minResolvableKeys: 60,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('boomer', 1, {
  minResolvableKeys: 59,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})

// tasks.md slice 27 (design.md §15's slice 26) — body batch 4 (final): skeleton, zombie. Both
// have a real `.layers.bb` (design §0: "roster grew," no longer `--from-vector` cases). Both
// ALSO have a genuinely empty vector colormeta (verified directly against source, matching
// ninja/werewolf's own shape) yet real piece-referenced slots (`color1`/`colorGuante` for
// skeleton; `color1-3`/`colorGuante` for zombie) — slice 26's defect 2/3 fixes
// (`computeManifestSlots`'s union, `resolveTintHex`'s neutral-black fallback) apply to both
// automatically, with no further code change needed here. Correction 2 (apply-progress.md,
// 2026-08-18) applies here too: the default `pixelCheckSlot: 'color1'` is real for both and R8/
// R8-pixel now run and pass (not skipped) since the guard fix above. Accessories (slice 31,
// partial — `ghost`/`wraith` excluded, blocked): both compiled cleanly, same `minnieHat`/`pet09`
// choice as the rest of the roster.
describeCharacterMatrix('skeleton', 13, {
  minResolvableKeys: 58,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})
describeCharacterMatrix('zombie', 17, {
  minResolvableKeys: 57,
  hatKey: 'minnieHat',
  petKey: 'pet09',
  expectedPetSide: 'right',
})

// tasks.md slice 21 task 9: every migration slice from 22 through 31 adds its character(s) here,
// e.g.:
//   describeCharacterMatrix('ghost', 6, { minResolvableKeys: <ghost's own sequence count> })
// A character compiled but not yet added to this list is NOT covered by R19 — report it as such,
// never implied covered (tasks.md slice 21 task 9 / design.md §19 risk 18).

test.describe('registry-mismatch reporting (design.md §7)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/harness.html')
    await page.waitForFunction(() => !!window.__avatarHarness)
  })

  test('an unregistered accessory is never silently created', async ({ page }) => {
    const socketId = `rasta_mismatch_${Date.now()}_${socketCounter++}`
    await page.evaluate(
      ({ socketId }) =>
        window.__avatarHarness.spawnAvatar({
          socketId,
          avatarId: 12,
          accessories: { hat: 'totallyUnknownHat', pet: 'totallyUnknownPet' },
        }),
      { socketId }
    )
    const state = await page.evaluate(
      ({ socketId }) => {
        window.__avatarHarness.setDirection(socketId, 'down')
        return window.__avatarHarness.readState(socketId)
      },
      { socketId }
    )
    const kinds = state.children.map((c) => c.kind)

    // No accessory child was created for either uncompiled/unregistered key — the container is
    // exactly {shadow, body, nameBackground, nameText}, never a placeholder or a crash.
    expect(kinds).toEqual(['shadow', 'body', 'nameBackground', 'nameText'])
  })
})

// Live-caught defect (tasks.md slices 28-31, apply-progress.md): `buildAccessoryPackagesFromGlob`
// used to overwrite (not accumulate) the `webp` role per registry key, so a multi-page accessory
// package (any hat needing >1 page — measured for real across the batch compile: most hats at 2
// pages, `rasta`'s own `pineappleHat` at 2) kept only ONE page's loader, and
// `AccessoryManager.load()` then patched EVERY atlas texture entry to that SAME single webp URL
// — page 1+'s frames would render page 0's pixel data cropped at the wrong coordinates. Fixed by
// making `webp` always an array (one loader per page, sorted so index matches page order,
// mirroring the body's own already-correct `groupLayeredActionKeyLoaders.js` precedent) and
// patching each atlas texture entry to ITS OWN page's URL by index.
test.describe('multi-page accessory loading (tasks.md slices 28-31 defect fix)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/harness.html')
    await page.waitForFunction(() => !!window.__avatarHarness)
  })

  // Fixture reassigned (accessory ss:1 rule, 2026-08-19): `rasta/pineappleHat` was 2 pages when
  // this test was written (slice 28) but is one of the 249 hats the whole-package ss:1 rule
  // recompiled — halving raster density shrank it to a single page, an expected, measured
  // consequence (see apply-progress.md's accessory ss:1 section), not a regression. Every one of
  // rasta's own 36 accessory packages is now 1 page (confirmed live), so no rasta fixture can
  // exercise this test's actual subject (distinct-image-data-per-page) any more; `boomer/mickeyHat`
  // is a REAL, currently-2-page package (confirmed live, unaffected by ss:1 since it stayed under
  // budget) that exercises the identical code path.
  test('a 2-page hat (boomer/mickeyHat) loads DISTINCT image data per page, not the same page repeated', async ({
    page,
  }) => {
    const socketId = `boomer_multipage_${Date.now()}_${socketCounter++}`
    await page.evaluate(
      ({ socketId }) =>
        window.__avatarHarness.spawnAvatar({
          socketId,
          avatarId: 1,
          accessories: { hat: 'mickeyHat' },
        }),
      { socketId }
    )
    await page.evaluate(({ socketId }) => window.__avatarHarness.setDirection(socketId, 'down'), {
      socketId,
    })

    const result = await page.evaluate(() => {
      const texture = window.game.textures.get('acc_boomer_hat_mickeyHat_atlas')
      return {
        pageCount: texture.source.length,
        // Each TextureSource's own `image.src` is the Blob object URL
        // `AccessoryManager.load()` patched onto that page's `atlas.json` frame group — distinct
        // per page after the fix, all identical (the defect) before it.
        sources: texture.source.map((s) => s.image.src),
      }
    })

    expect(result.pageCount, 'boomer/mickeyHat is compiled to 2 pages (measured live, 2026-08-19)').toBe(2)
    expect(new Set(result.sources).size, 'each page must load its OWN distinct image data').toBe(
      result.pageCount
    )
  })
})
