import Enum from './Enum';

const RequestSocketsEnum = new Enum({
    USER_MOVE: 'request:user_move',
    USER_CHANGE_UPPERCUT: 'request:user_change_uppercut',
    USER_CHANGE_COCONUT: 'request:user_change_coconut',
    MINIGAME_SUBSCRIBE: 'request:minigame_subscribe',
    GET_PUBLIC_SCENE_DATA: 'request:get_public_area_data',
    USER_SELECT_USER: 'request:user_select_user',
    SEND_UPPERCUT: 'request:send_uppercut',
    USER_LEAVE_SCENE: 'request:user_leave_area',
    LOGIN: 'login',
    REGISTER: 'register',
    GET_PUBLIC_SCENES: 'get_public_areas',
    JOIN_PUBLIC_SCENE: 'request:join_public_area',
    SEND_EMOJI: 'request:send_emoji',
    SEND_CHAT: 'request:send_chat',
    SEND_COCONUT: 'request:send_coconut',
    CHANGE_LOOK: 'request:change_look',
    GET_GAME_SCENES: 'request:get_game_scenes',
    ISLAND_CREATE: 'request:island_create',
    GET_MY_ISLANDS: 'request:get_my_islands',
    JOIN_ISLAND: 'request:join_island',
    PRIVATE_SCENE_CREATE: 'request:private_scene_create',
    JOIN_PRIVATE_SCENE: 'request:join_private_scene',
    SCENE_PUT_ITEM: 'request:scene_put_item',
    SCENE_REMOVE_ITEM: 'request:scene_remove_item',
    GET_PUBLIC_ISLANDS: 'request:get_public_islands',
    GET_MINIGAME_SUBSCRIBE_STATUS: 'request:get_minigame_subscribe_status',
    USER_UPDATE_DESCRIPTION: 'request:user_update_description',
    USER_CATCH_ITEM: 'request:user_catch_item',
    USER_CHANGE_FICHA: 'request:user_change_ficha',
    USER_CHANGE_CHAT: 'request:user_change_chat',
    USER_CHANGE_NAME_COLOR: 'request:user_change_name_color',
    USER_CHANGE_SHADOW_COLOR: 'request:user_change_shadow_color',
    REFRESH_USERS_SCENE_CHAT_LIST: 'request:refresh_users_scene_chat_list',
    REFRESH_USER_CREDITS: 'request:refresh_user_credits',
    LOGIN_OAUTH: 'request:login_oauth',
    JWT_AUTO_LOGIN: 'request:jwt_auto_login',
    LOGOUT: 'request:logout',
    LOBBY_GACHA_SPIN: 'request:lobby_gacha_spin',
    GET_GACHA_PRIZES: 'request:get_gacha_prizes',
    GET_USER_DECORATIONS: 'request:get_user_decorations',
    ROTATE_OBJECT: 'request:rotate_object',
    SETTINGS_UPDATE_NAME: 'request:settings_update_name',
    SETTINGS_UPDATE_GRAPHICS: 'request:settings_update_graphics',
    SETTINGS_UPDATE_LANG: 'request:settings_update_lang',
    USER_SEND_INTERACTION: 'request:user_send_interaction',
    USER_ACCEPT_INTERACTION: 'request:user_accept_interaction',
    USER_REJECT_INTERACTION: 'request:user_reject_interaction',
    USER_CANCEL_INTERACTION: 'request:user_cancel_interaction',
    GET_USER_AVATARS: 'request:get_user_avatars',
    USER_CHANGE_AVATAR: 'request:user_change_avatar',
});

export default RequestSocketsEnum;