[PHP]
; Deshabilitar Opcache para el entorno de desarrollo, para que los cambios en los archivos se reflejen al instante.
; opcache.enable=0
upload_max_filesize=100M
post_max_size=100M
max_execution_time=300
memory_limit=512M