# Nombre del proyecto
sonar.projectKey=BoomMania
sonar.projectName="BoomMania"
sonar.organization=BoomMania

# Source route
sonar.sources=.

# Sonar host url
sonar.host.url=http://localhost:9000

# Language
# We've commented this out, because we want to analyse both PHP and Javascript
sonar.language=php

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Versión del proyecto
sonar.projectVersion=1.0

# Rutas de código fuente
sonar.sources=app

# Project token
sonar.login=sqp_0a81491d998776eb36831f805a36c7b5887e5830

# Excluir carpetas específicas
sonar.exclusions=app/Providers/**, docker-conf/**, bootstrap/**, storage/**, vendor/**, node_modules/**
